bind = "0.0.0.0:25565"
spawn_dimension = "end"
welcome_message = "Welcome to PicoLimbo!"
default_game_mode = "spectator"

[forwarding.velocity]
enabled = true
secret = "y1nyoG9y5TppU0l2qt9GDf7eKaRhlOEB"

[forwarding.bungee_cord]
enabled = false
bungee_guard = false
tokens = []

[server_list]
max_players = 20
message_of_the_day = "A Minecraft Server"
show_online_player_count = true
